services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres2
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  skycloud:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres/postgres2
      - CORE_HOSTNAME=0.0.0.0
    depends_on:
      - postgres
    volumes:
      - './uploads:/skycloud/uploads'
      - './public:/skycloud/public'
      - './themes:/skycloud/themes'

volumes:
  pgdata:
