services:
  skycloud:
    build:
      context: .
    restart: unless-stopped
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - './uploads:/skycloud/uploads'
      - './public:/skycloud/public'
      - './themes:/skycloud/themes'

volumes:
  pgdata:
