blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://github.com/diced/skycloud/discussions/new?category=ideas&title=Your%20brief%20description%20here&labels=feature
    about: Ask for a new feature
  - name: SkyCloud Discord
    url: https://discord.gg/EAhCRfGxCF
    about: Ask for help with anything related to SkyCloud!
  - name: SkyCloud Docs
    url: https://skycloud.diced.sh
    about: Maybe take a look a the docs?
